app:
  port: 3333
  displayZeroDays: true # отображение дней с нулевыми сессиями

db:
  addr: "localhost:5432"
  user: root
  pass: root
  dbname: dbname

integrations:
  - name: wakatime
    # включена ли интеграция
    enabled: false
    # апи ключ
    api_key: your_api_key
    # таймаут получения данных в секундах
    timeout: 10 

  - name: monkeytype
    enabled: false
    api_key: your_api_key
    timeout: 10


pomodoro:
  # через сколько минут напомнить о начале рабочей сессии
  startSessionReminder: 5 

  workMinutes: 5
  shortBreakMinutes: 3
  longBreakMinutes: 10

  breakAfterSessions: 2

  sessionsGoal: 2

